export const projectsList = [
    {
      name: 'nakeman.cn',
      date: '2023',
      demo: 'http://nakeman.cn',
      url: 'http://nakeman.cn',
      description: 'My personal website build by Gatsby React and Tailwind.',
      description_cn: '个人技术博客源码，基于Gatsby React和 Tailwind开发，设计独特，性能卓越，SEO友好，Markdown内容管理方便。',
      source:'https://github.com/nakeman/nakeman.cn',
      document:'/blog/nakeman-blog-migrate-from-wordpress-to-gatsby/',
      image: 'nakeman.jpg',
      highlight: true,
    },
    {
      name: 'youlike',
      date: '2021',
      description: 'An simple and easy online survey app.',
      description_cn: '一支可高度定制的在线问卷应用（未完成）。',
      source: 'https://github.com/nakeman/youlike',
      highlight: false,
    },
    {
      name: 'linknote',
      date: '2021',
      description: 'A note-taking tool to help you study and research.',
      description_cn: 'linknote，联想笔记，是一支旨在协助和提高学习者或研究工作者作业效率的笔记工具。使用Node Express MongoDB开发。',
      source: 'https://github.com/nakeman/linknote',
      image: 'linknote.png',
      highlight: true,
    },
    {
      name: 'modular-web-frontend-webpack-js',
      date: '2022',
      description: 'Web dev tutorial source on morden modularize method in : vanilla JS, React, and Vue.',
      description_cn: '《前端模块化开发实验》系列教程源码',
      source:'https://github.com/nakeman/modular-web-frontend-webpack-js',
      document:'/blog/modular-web-frontend-webpack-js',
      highlight: false,
    },
    {
      name: 'base-style-design-collections',
      date: '2022',
      description: 'collecting Web UI css base style design examples',
      description_cn: 'CSS base style 研究实验项目（未完成）。',
      source:'https://github.com/nakeman/base-style-design-collections',
      document:'',
      highlight: false,
    },
    {
      name: 'sugeladi.net',
      date: '2019',
      description: 'sugeladi.net new version prototype',
      description_cn: '苏格拉底网新版设计模型',
      image: 'sugeladi.png',
      source:'https://github.com/nakeman/sugeladi.net',
      document:'',
      highlight: false,
    },
  ]