export const projectsList = [
    {
      name: 'nakeman.cn',
      date: '2023',
      demo: 'http://nakeman.cn',
      url: 'http://nakeman.cn',
      description: 'My personal website build by Gatsby React Tailwind and Node.',
      source:'https://github.com/nakeman/nakeman.cn',
      document:'',
      highlight: true,
    },
    {
      name: 'youlike',
      date: '2021',
      description: 'An simple and easy online survey app.',
      source: 'https://github.com/nakeman/youlike',
      highlight: true,
    },
    {
      name: 'linknote',
      date: '2021',
      description: 'A note-taking tool to help you study and research.',
      source: 'https://github.com/nakeman/linknote',
      highlight: true,
    },
    {
      name: 'modular-web-frontend-webpack-js',
      date: '2022',
      demo: 'http://nakeman.cn',
      url: 'http://nakeman.cn',
      description: 'Web dev tutorial source on morden modularize method in : vanilla JS, React, and Vue.',
      source:'https://github.com/nakeman/modular-web-frontend-webpack-js',
      document:'',
      highlight: true,
    },
    {
      name: 'base-style-design-collections',
      date: '2022',
      demo: 'http://nakeman.cn',
      url: 'http://nakeman.cn',
      description: 'collecting Web UI css base style design examples',
      source:'https://github.com/nakeman/base-style-design-collections',
      document:'',
      highlight: true,
    },
  ]